version: "3.2"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../main.env
    # environment:
    #   - AMQPS=${AMQPS}
    command: "python main.py"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
        # condition: service_healthy

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../main.env
    # environment:
    #   - AMQPS=${AMQPS}
    command: "python consumer.py"
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    # environment:
    #   MYSQL_DATABASE: main
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: root
    #   MYSQL_ROOT_PASSWORD: root
    env_file:
      - ../main.env
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    # healthcheck:
    #   test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
    #   interval: 2s
    #   timeout: 30s
    #   retries: 15
    logging:
      driver: none

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 5556:80
  #   environment:
  #     PMA_HOST: db
  #   logging:
  #     driver: "none"
