version: "3.2"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../admin.env
    # command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
        # condition: service_healthy
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../admin.env
    command: "python consumer.py"
    depends_on:
      - db
  proxy:
    build:
      context: ./nginx
    ports:
      - "8090:80"
    depends_on:
      - backend
  db:
    image: mysql:5.7.22
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ../admin.env
    # healthcheck:
    #   test: '/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute "SHOW DATABASES";'
    #   interval: 2s
    #   timeout: 30s
    #   retries: 15
    logging:
      driver: "none"

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 5555:80
  #   environment:
  #     PMA_HOST: db
  #   logging:
  #     driver: "none"
