version: "3.2"
services:
  reverse-proxy:
    image: nginx
    build:
      context: .
      dockerfile: Dockerfile-deploy
    volumes:
      - ./proxy-conf/default-deploy.conf:/etc/nginx/conf.d/default.conf
      # - ./proxy-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
volumes:
  proxy-conf:
networks:
  default:
    name: micro-network
